version: "3.6"
services:

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: unless-stopped
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: it@facharztpraxis-fuer-allgemeinmedizin.de
    depends_on:
      - nginx-proxy

  app:
    restart: always
    image: myffa/ffa:latest
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
      - appdata:/usr/app/pub
    environment:
      - APP_ENC_KEY=${APP_ENC_KEY}
      - VIRTUAL_HOST=facharztpraxis-fuer-allgemeinmedizin.de,www.facharztpraxis-fuer-allgemeinmedizin.de
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=facharztpraxis-fuer-allgemeinmedizin.de
      - LETSENCRYPT_EMAIL=it@facharztpraxis-fuer-allgemeinmedizin.de
    links:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodata:/data/db
      - ./init:/docker-entrypoint-initdb.d
      - ./init/mongod.conf:/etc/mongod.conf:ro
   
networks:
  default:
    external:
      name: ffa-app-network

volumes:
  mongodata:
    name: ffa-mongo-data

  appdata:
    name: ffa-app-data