version: "3.6"
services:

  app:
    restart: always
    build: ./app
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
      - appdata:/app/pub
    links:
      - mongo
  

  mongo:
    image: mongo
    container_name: mongo
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodata:/data/db
      - ./init:/docker-entrypoint-initdb.d
      - ./init/mongod.conf:/etc/mongod.conf:ro
    ports:
      - "27017:27017"
   

volumes:
  mongodata:
    name: ffa-mongo-data

  appdata:
    name: ffa-app-data