version: "3.6"
services:

  mongo:
    image: mongo
    container_name: mongo
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - /var/jenkins_home/workspace/ffa-app/init:/docker-entrypoint-initdb.d:ro
      - mongodata:/data/db
      - ./init/mongod.conf:/etc/mongod.conf:ro
    ports:
      - "27017:27017"
   

volumes:
  mongodata:
    name: ffa-mongo-data