import { NgModule } from '@angular/core';

import {
  MatButtonModule,
  MatMenuModule,
  MatToolbarModule,
  MatSidenavModule,
  MatIconModule,
  MatCardModule, 
  MatListModule, 
  MatGridListModule, 
  MatFormFieldModule, 
  MatInputModule, 
  MatProgressSpinnerModule, 
  MatCheckboxModule, 
  MatTooltipModule, 
  MatProgressBarModule, 
  MatDialogModule, 
  MatSnackBarModule, 
  MatSelectModule, 
  MatExpansionModule, 
  MatTableModule, 
  MatSortModule, 
  MatPaginatorModule,
  MatTreeModule, 
  MatChipsModule,
  MatTabsModule,
  MatDatepickerModule,
  MatNativeDateModule , 
  MatAutocompleteModule
} from '@angular/material';


@NgModule({
  imports: [
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatSidenavModule,
    MatIconModule,
    MatCardModule, 
    MatListModule, 
    MatGridListModule, 
    MatFormFieldModule, 
    MatInputModule, 
    MatProgressSpinnerModule, 
    MatCheckboxModule, 
    MatTooltipModule, 
    MatProgressBarModule, 
    MatDialogModule, 
    MatSnackBarModule, 
    MatSelectModule, 
    MatExpansionModule, 
    MatTableModule, 
    MatSortModule, 
    MatPaginatorModule,
    MatTreeModule, 
    MatChipsModule,
    MatTabsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatAutocompleteModule
  ],
  exports: [
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatSidenavModule,
    MatIconModule,
    MatCardModule, 
    MatListModule, 
    MatGridListModule, 
    MatFormFieldModule, 
    MatInputModule, 
    MatProgressSpinnerModule, 
    MatCheckboxModule, 
    MatTooltipModule, 
    MatProgressBarModule, 
    MatDialogModule, 
    MatSnackBarModule, 
    MatSelectModule, 
    MatExpansionModule, 
    MatTableModule, 
    MatSortModule, 
    MatPaginatorModule,
    MatTreeModule, 
    MatChipsModule,
    MatTabsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatAutocompleteModule
  ], 
  providers : [
    MatDatepickerModule
  ]
})
export class MaterialModule {}